### ISSUE TITLE
Login Failure Bad or Missing Credential

### ISSUE THREAD

**Issue by SUBnet192** [Texiwill/aac-lib#15] opened 2022-03-18 17:52 UTC
First time experimenting with WSL, installed on W10, script runs fine but will not login. I even changed my password to something less complex, no go. 

vsm.sh -y --vexpertx --historical --patches --dts --oem  --symlink --compress --repo /mnt/x/Xfers/VMware

is the command I use. I tried specifying the creds on cmdline with no success either. Any insight?

**Comment by Texiwill** [comment] 2022-03-18 17:54
Hello,

Are you using WSL2 or WSL? Also, what OS?

Best regards,
Edward L Haletky

**Comment by SUBnet192** [comment] 2022-03-18 17:56
Windows 10 and WSL2

**Comment by SUBnet192** [comment] 2022-03-18 18:12
W11 installed, no luck.
 ran --clean to purge config/creds, and restarted again:

Authenticating... May take up to 90s... 12-20s is normal...
Installing necessary modules
Finished installing necessary modules
Login Failure Bad or Missing Credential

**Comment by Texiwill** [comment] 2022-03-18 18:38
So inside WSL2 you picked a specific version of Linux, which was it? W10/W11 is the outer OS, WSL2 has a virtualized OS in use, which was it?

**Comment by SUBnet192** [comment] 2022-03-18 18:40
ubuntu

**Comment by Texiwill** [comment] 2022-03-18 18:45
Which version of Ubuntu?

**Comment by SUBnet192** [comment] 2022-03-18 18:57
Sorry, the output of vsm shows:

version 6.6.3
OS mode: ubuntu

**Comment by Texiwill** [comment] 2022-03-18 19:00
use the following command:
`grep VERSION /etc/os-release`

**Comment by SUBnet192** [comment] 2022-03-18 19:01
20.04.4 LTS (FOcal Fossa)

**Comment by SUBnet192** [comment] 2022-03-18 19:01
should I switch to another? Debian?

**Comment by Texiwill** [comment] 2022-03-18 19:02
no, that should work. Need to do some tests.

**Comment by Texiwill** [comment] 2022-03-31 16:16
I cannot duplicate this issue. I used a fresh install of Ubuntu 20.04.4 LTS on Windows 10. Using a fresh install of LinuxVSM (6.7.0) which has no changes for WSL2. Did you use the 'install.sh' to install LinuxVSM? There sounds like something is missing.

**Comment by SUBnet192** [comment] 2022-04-05 16:48
Indeed, I get no resolution for myvmware.vmware.com

But I can resolve vmware.com and anything else. I assume you meant my.vmware.com?

Marc

From: Edward Haletky ***@***.***>
Date: Tuesday, April 5, 2022 at 12:40 PM
To: Texiwill/aac-lib ***@***.***>
Cc: Marc Bouchard ***@***.***>, Author ***@***.***>
Subject: Re: [Texiwill/aac-lib] Login Failure Bad or Missing Credential (Issue #15)

Several questions:

  *   are you attempting to use LinuxVSM through a generic VPN?
  *   can you ping or reach myvmware.vmware.com from your WSL2 window?

It looks like it cannot resolve or reach myvmware.vmware.com.

**Comment by Texiwill** [comment] 2022-04-05 17:05
Apologies, yes my.vmware.com. you are resolving from the debian WSL2? I cannot reproduce on any WSL2 installation. What version of Windows are you using?

**Comment by Texiwill** [comment] 2022-04-05 17:28
I removed all WSL2 items and started fresh with a newly patched W10. Let's stick to that version.

**Closed** 2022-07-27 18:21 UTC
